### ISSUE TITLE
Unable to Create Config File on Start

### ISSUE THREAD

**Issue by HerrMagiic** [roflmuffin/CounterStrikeSharp#101]
### Description:
CounterStrike Sharp encounters a startup issue preventing the creation of the configuration file. The error cites a `FileNotFoundException` related to the System.Text.Json assembly version 8.0.0.0. Additionally, the plugin's config folder is not being generated.

### Environment:
- Docker container
- SteamRT3 Sniper image for Counter-Strike 2

### Investigation:
- Verified correct user permissions. The user can create files and folders in that directory.
- Reinstalled CounterStrike Sharp with runtime (v56).
- Confirmed the presence of `System.Text.Json.dll` in `counterstrikesharp/dotnet/shared/Microsoft.NETCore.App`.

### Expected Behavior:
CounterStrike Sharp should successfully create the WeaponBalance plugin configuration file during startup.

### Error Message:
```
Plugin path: /home/container/game/csgo/addons/counterstrikesharp/plugins/WeaponBalance/WeaponBalance.dll
Loading plugin: WeaponBalance
Failed to generate configuration file for WeaponBalance: System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element, Boolean inherit)
   at System.Text.Json.Serialization.Metadata.ReflectionJsonTypeInfo`1.CreateProperty(Type typeToConvert, MemberInfo memberInfo, JsonSerializerOptions options, Boolean shouldCheckForRequiredKeyword)
   at System.Text.Json.Serialization.Metadata.ReflectionJsonTypeInfo`1.LateAddProperties()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropertyCache()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at CounterStrikeSharp.API.Modules.Config.ConfigManager.Load[T](String pluginName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs:line 57
Failed to parse configuration 'WeaponBalance': System.IO.FileNotFoundException: Could not find file '/home/container/game/csgo/addons/counterstrikesharp/configs/plugins/WeaponBalance/WeaponBalance.json'.
File name: '/home/container/game/csgo/addons/counterstrikesharp/configs/plugins/WeaponBalance/WeaponBalance.json'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at CounterStrikeSharp.API.Modules.Config.ConfigManager.Load[T](String pluginName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs:line 69
WeaponBalance has been loaded, and the hot reload flag was True, path is /home/container/game/csgo/addons/counterstrikesharp/plugins/WeaponBalance/WeaponBalance.dll
```

**Comment by roflmuffin** [comment]
This error indicates that the plugin you are trying to load has been compiled for .NET 8 (based on the system.json version), while our runtime is using .NET 7 and is not forwards compatible. Please compile the plugin with .NET 7 SDKD and try again.

**Comment by HerrMagiic** [comment]
> This error indicates that the plugin you are trying to load has been compiled for .NET 8 (based on the system.json version), while our runtime is using .NET 7 and is not forwards compatible. Please compile the plugin with .NET 7 SDK and try again.

In the .csproj is the TargetFramework net7.0 this should be right, right?
Or do i missunderstood you?

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FileVersion>0.0.6</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.56" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
  </ItemGroup>

</Project>
```

**Comment by KillStr3aK** [comment]
> <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />

🧐

**Comment by HerrMagiic** [comment]
Working now, Thanks!❤️
