### ISSUE TITLE
Some signatures needs wildcard bytes

### ISSUE THREAD

**Issue by KillStr3aK** [roflmuffin/CounterStrikeSharp#123]
Some signatures are off by some bytes and results in invalid function pointer exception, I'll update this list when needed

- [ ] `CBaseModelEntity`.`SetModel`
- [ ] `UTIL_CreateEntityByName`

**Comment by crashzk** [comment]
For the record only.
```
[39;49m�[40m�[39;49m�[36m�[40mCounterStrikeSharp.API.Core.NativeException: Could not find signature

at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176

[39;49m�[39;49m�[40m�[39;49m�[36m�[40mCounterStrikeSharp.API.Core.NativeException: Could not find signature

at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
```

**Comment by crashzk** [comment]
I don't know if it helps, but apparently the error is now showing the signature with an error.
```
[39;49m[40m[39;49m[36m[40mCounterStrikeSharp.API.Core.NativeException: Could not find signature \x55\x48\x89\xF2\x48\x89\xE5\x41\x54\x49\x89\xFC\x48\x8D\x7D\xE0\x48\x83\xEC\x18\x48\x8D\x05\xA5

at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176

[39;49m[39;49m[40m[39;49m[36m[40mCounterStrikeSharp.API.Core.NativeException: Could not find signature \x48\x8D\x05\xC9\xC2\xBC

at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
```
