### ISSUE TITLE
[BUG] Error log | Could not find signature

### ISSUE THREAD

**Issue by crashzk** [roflmuffin/CounterStrikeSharp#124]
```
[39;49m[40m[39;49m[36m[40mCounterStrikeSharp.API.Core.NativeException: Could not find signature

at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176

[39;49m[39;49m[40m[39;49m[36m[40mCounterStrikeSharp.API.Core.NativeException: Could not find signature

at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
```
Apparently a signature error, or missing?

**Comment by KillStr3aK** [comment]
related to #123
