### ISSUE TITLE
Error css v126

### ISSUE THREAD

**Issue by scorp1onul** [roflmuffin/CounterStrikeSharp#201]
Hello,
After last update of css i receive this error and also crash

 ```
2023-12-14 15:10:14.964 +02:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Advertisement.Ads.EventCsWinPanelRound(EventCsWinPanelRound handle, GameEventInfo info)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```

**Comment by ezekutor** [comment]
Advertisement.Ads.EventCsWinPanelRound

**Comment by scorp1onul** [comment]
Thank you, i will remove that system until fix, i m at work now and i didn t have time for searching to be honest.

Have a nice day
