### ISSUE TITLE
server random crashs

### ISSUE THREAD

**Issue by cyberaboud** [roflmuffin/CounterStrikeSharp#213]
i don't know what happened but i got this error 

RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 213] removing change '3/7/44' for field m_PredNetByteVariables[44] (value '0') on array that has metadata with only 43 array elements!
RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 398] removing change '3/21/10' for field m_OwnerOnlyPredNetFloatVariables[10] (value '-2.8026e-45') on array that has metadata with only 10 array elements!

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at CounterStrikeSharp.API.Core.Helpers.InvokeNative(IntPtr)
--------------------------------
   at CounterStrikeSharp.API.Core.ScriptContext.InvokeNativeInternal()
   at CounterStrikeSharp.API.Core.ScriptContext.Invoke()
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr, System.Object[])
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternalVoid(System.Object[])
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`3[[System.IntPtr, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[CounterStrikeSharp.API.Modules.Entities.Constants.RoundEndReason, CounterStrikeSharp.API, Version=1.0.129.0, Culture=neutral, PublicKeyToken=null],[System.Single, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(IntPtr, CounterStrikeSharp.API.Modules.Entities.Constants.RoundEndReason, Single)
   at DynamicClass.InvokeStub_Action.Invoke(System.Object, System.Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at CounterStrikeSharp.API.Core.FunctionReference+<>c__DisplayClass3_0.<.ctor>b__0(CounterStrikeSharp.API.Core.fxScriptContext*)

**Comment by roflmuffin** [comment]
I would first investigate what plugin is causing this issue

**Comment by Gorbanev9999** [comment]
> n

Haven't found a solution?
