### ISSUE TITLE
System.Reflection.TargetInvocationException thrown when accessing fields of `@event.Userid` in a GameEventHandler

### ISSUE THREAD

**Issue by miguno** [roflmuffin/CounterStrikeSharp#26]
The server throws an exception when trying to use the simple [GampleEventHandler from the docs](https://docs.cssharp.dev/features/game-events/). The only change is that I used `Console.Writeln()` instead of the `Log()` method in the example. The exception is thrown when the `@event` is being read.

```csharp
[GameEventHandler]
public HookResult OnPlayerConnect(EventPlayerConnect @event, GameEventInfo info) {
  // This works:
  Server.PrintToChatAll($"Player {@event.Name} has connected!");

  // But this will trigger an exception:
  Server.PrintToChatAll($"{@event.Userid.IsBot} will trigger an exception!");

  // @event.Userid will give you a reference to a CCSPlayerController class.
  // However, accessing any of its fields will throw an exception!
  HookResult.Continue;
}
```

Exception:

```
Creating NetChan for user 0 'm0NESY' @ 192.168.0.44:59053
Associating NetChan       m0NESY    192.168.0.44:59053[1] (192.168.0.44:59053) wit
CServerSideClientBase::Connect( name='m0NESY', userid=0, fake=0, chan->addr=192.16
Client 0 'm0NESY' signon state SIGNONSTATE_NONE -> SIGNONSTATE_CONNECTED
Server waking up from hibernation
L 11/05/2023 - 19:50:43: "m0NESY<0><[U:1:81210237]><>" connected, address "192.168
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type, Byte* ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Script
Context.cs:line 407
   at CounterStrikeSharp.API.Core.ScriptContext.GetResultHelper(fxScriptContext* context, Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrike
Sharp.API/Core/ScriptContext.cs:line 391
   at CounterStrikeSharp.API.Core.ScriptContext.GetResultHelper(Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptConte
xt.cs:line 384
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:
line 370
   at CounterStrikeSharp.API.Core.NativeAPI.GetSchemaValueByName[T](IntPtr instance, Int32 returntype, String classname, String propname) in /__w/CounterStrikeSharp/Cou
nterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 868
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaValue[T](IntPtr handle, String className, String propertyName) in /__w/CounterStrikeSharp/CounterStrikeSharp
/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 26
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetString(IntPtr pointer, String className, String memberName) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/
CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 79
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_PlayerName() in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:
line 4308
   at MigunoPlugin.MigunoPlugin.OnPlayerConnect(EventPlayerConnect event, GameEventInfo info) in /Users/miguno/git/cs2miguno/MigunoPlugin/MigunoPlugin.cs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/Cou
nterStrikeSharp.API/Core/FunctionReference.cs:line 70
```

Environment:
- Debian GNU/Linux 12 (bookworm) x86_64
- Kernel: 6.1.0-13-amd64

Have you come across this error before?

PS: Thank you for the work on this project! :-)

**Comment by KillStr3aK** [comment]
May I ask on what platform the server is running? (Also for issues like this you may want to join the discord for faster support)

**Comment by miguno** [comment]
Doh, I forgot to add the environment information.

```
Debian GNU/Linux 12 (bookworm) x86_64
Kernel: 6.1.0-13-amd64
```

Discord server: Noted, thanks!

**Comment by roflmuffin** [comment]
I think this may have been an error in this specific version, would you be able to update to the latest and see if the error persists?

**Comment by miguno** [comment]
I tried the [latest version](https://github.com/roflmuffin/CounterStrikeSharp/actions/runs/6800197325), but same result:


```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type, Byte* ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 407
   at CounterStrikeSharp.API.Core.ScriptContext.GetResultHelper(fxScriptContext* context, Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 391
   at CounterStrikeSharp.API.Core.ScriptContext.GetResultHelper(Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 384
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 370
   at CounterStrikeSharp.API.Core.NativeAPI.GetSchemaValueByName[T](IntPtr instance, Int32 returntype, String classname, String propname) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 868
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaValue[T](IntPtr handle, String className, String propertyName) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 27
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetString(IntPtr pointer, String className, String memberName) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 80
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_PlayerName() in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 4680
   at MigunoPlugin.MigunoPlugin.OnPlayerConnect(EventPlayerConnect event, GameEventInfo info) in /Users/miguno/git/cs2miguno/MigunoPlugin/MigunoPlugin.cs:line 37
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 70
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type, Byte* ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 407
   at CounterStrikeSharp.API.Core.ScriptContext.GetResultHelper(fxScriptContext* context, Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 391
   at CounterStrikeSharp.API.Core.ScriptContext.GetResultHelper(Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 384
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 370
   at CounterStrikeSharp.API.Core.NativeAPI.GetSchemaValueByName[T](IntPtr instance, Int32 returntype, String classname, String propname) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 868
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaValue[T](IntPtr handle, String className, String propertyName) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 27
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetString(IntPtr pointer, String className, String memberName) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 80
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_PlayerName() in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 4680
   at MigunoPlugin.MigunoPlugin.OnPlayerConnect(EventPlayerConnect event, GameEventInfo info) in /Users/miguno/git/cs2miguno/MigunoPlugin/MigunoPlugin.cs:line 37
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 70
```

**Comment by gardc** [comment]
Getting same exception! Running on DatHost cs2 server.

**Comment by miguno** [comment]
Accessing `@event.Name` works successfully in `OnPlayerConnect`:

```csharp
Server.PrintToChatAll($"Player {@event.Name} has connected! (@event.Name)");
```

But accessing the `CCSPlayerController` of the connecting player via `@event.Userid` does not:

```csharp
// Triggers:
// System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. (see above)
Server.PrintToChatAll($"Player {@event.Userid.PlayerName} has connected! (@event.Userid.PlayerName)");
```

**Comment by hobsRKM** [comment]
Same issue using example form official docs on linux server

**Comment by KillStr3aK** [comment]
this is a barebone example, open [Entity Pointers & Handles](https://docs.cssharp.dev/reference/referencing-players/#entity-pointers--handles)

**Comment by miguno** [comment]
@KillStr3aK : Now that I have more experience with CSS, I know what I have to do. However, as a beginner, this was an unneeded roadblock.  Certainly, the documentation should not include code examples that *will not work* as shown.  I opened a PR to fix the docs.
