### ISSUE TITLE
Error on latest build

### ISSUE THREAD

**Issue by xLeviNx** [roflmuffin/CounterStrikeSharp#300]
```
14:15:03 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Modules.Utils.CHandle`1.get_IsValid() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Utils/CHandle.cs:line 56
   at CounterStrikeSharp.API.Modules.Entities.EntitySystem.GetEntityByHandle[T](CHandle`1 handle) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/EntitySystem.cs:line 29
   at CounterStrikeSharp.API.Modules.Utils.CHandle`1.get_Value() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Utils/CHandle.cs:line 52
   at SLAYER_ZombieRiot.SLAYER_ZombieRiot.<>c__DisplayClass44_0.<Zombify>b__0() in /home/levin/csharp/zombieriot/SLAYER_ZombieRiot.cs:line 661
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```

```
  CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.
  Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison, source2gen and CS2Fixes.
  See ACKNOWLEDGEMENTS.md for more information.
  Current API Version: 159
```

`  List of all plugins currently loaded by CounterStrikeSharp: 2 plugins loaded.
  [#1:LOADED]: "Zombie Riot" (1.0) by LevHost Gaming
    Humans stick together to fight off zombie attacks
  [#2:LOADED]: "Resource Precacher" (1.0.3 (release)) by Nexd @ Eternar (https://eternar.dev)
    Automatically precache resources.`

**Comment by B3none** [comment]
What are you doing on `/zombieriot/SLAYER_ZombieRiot.cs:line 661`

**Comment by xLeviNx** [comment]
> What are you doing on `/zombieriot/SLAYER_ZombieRiot.cs:line 661`

`if(player.PlayerPawn.Value.WeaponServices!.MyWeapons.Count != 0)player.RemoveWeapons(); // Remove all weapons of Player (Zombie)`

Although this doesn't seem to be an issue with just this. Happens periodically on all servers

**Comment by B3none** [comment]
You need to add additional validation to the player pawn and weapon services access
