### ISSUE TITLE
Help with admin.json 

### ISSUE THREAD

**Issue by mayersgamer** [roflmuffin/CounterStrikeSharp#303]
- after 3 months of runing multiple cs2 server i still cannot understand how admin.json and admingroups.json work
-  the only way im adding admin is by database plugin.
- every time i add the second admin in admin.json  everyone else lose permission , it is like i broke the code in admin.json but i still dont know where ? 
- here is an exemple of my current admin.json file : 
-
{
  "Erikj": {
    "identity": "76561198097507043",
    "immunity": 100,
    "flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ],
    "groups": [
      "#css/admin"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": false
    }
  },
  "Another erikj": {
    "identity": "76561199187061311",
    "flags": ["@css/generic", "@css/kick]
  }
}

console : 

16:34:25 [INFO] (cssharp:Core) Loading Admins from /home/steam/csgo-ds/game/csgo/addons/counterstrikesharp/configs/admins.json
16:34:25 [EROR] (cssharp:AdminManager) Failed to load admin data
System.Text.Json.JsonException: '0x0A' is invalid within a JSON string. The string should be correctly escaped. Path: $['Another erikj'].flags[1] | LineNumber: 28 | BytePositionInLine: 41.
 ---> System.Text.Json.JsonReaderException: '0x0A' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 28 | BytePositionInLine: 41.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at CounterStrikeSharp.API.Modules.Admin.AdminManager.LoadAdminData(String adminDataPath) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Admin/AdminPermissions.cs:line 129
16:34:25 [INFO] (cssharp:Core) Loading Admin Groups from /home/steam/csgo-ds/game/csgo/addons/counterstrikesharp/configs/admin_groups.json
Loaded 1 admin groups.
16:34:25 [INFO] (cssharp:Core) Loading Admin Command Overrides from /home/steam/csgo-ds/game/csgo/addons/counterstrikesharp/configs/admin_overrides.json
Admin command overrides file not found. Skipping admin command overrides load.

aghh !! Help

**Comment by mayersgamer** [comment]
{
  "Erikj": {
    "identity": "76561198097507043",
    "immunity": 100,
    "flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": false
    }
  },
  "ketchup": {
    "identity": "76561199187061311",
    "flags": ["@css/reservation", "@css/generic", "@css/kick", "@css/ban", "@css/unban", "@css/vip", "@css/slay", "@css/changemap", "@css/vote", "@css/cheats" ],
    "immunity": 100
  },
  "timox": {
    "identity": "76561198185669765",
    "flags": ["@css/reservation", "@css/generic", "@css/kick", "@css/ban", "@css/unban", "@css/vip", "@css/slay", "@css/changemap", "@css/vote", "@css/cheats" ],
    "immunity": 100
  },
  "ketchup": {
    "identity": "76561199187061311",
    "flags": ["@css/reservation", "@css/generic", "@css/kick", "@css/ban", "@css/unban", "@css/vip", "@css/slay", "@css/changemap", "@css/vote", "@css/cheats" ],
    "immunity": 100
  },
  "twig": {
    "identity": "76561199042164403",
    "flags": ["@css/reservation", "@css/generic", "@css/kick", "@css/ban", "@css/unban", "@css/vip", "@css/slay", "@css/changemap", "@css/vote", "@css/cheats" ],
    "immunity": 100
  },
  "freeslot": {
    "identity": "76561198169213199",
    "flags": ["@css/reservation", "@css/generic", "@css/kick", "@css/ban", "@css/unban", "@css/vip", "@css/slay", "@css/changemap", "@css/vote", "@css/cheats" ],
    "immunity": 100
  },
  "freeslot2": {
    "identity": "76561198169213199",
    "flags": ["@css/reservation", "@css/generic", "@css/kick", "@css/ban", "@css/unban", "@css/vip", "@css/slay", "@css/changemap", "@css/vote", "@css/cheats" ],
    "immunity": 100
  }

}


i have done it !!!! after 33333333333 months !!!

**Comment by mino9421** [comment]
i have a problem in my logs, its a fresh server and I followed a tutorial to setup what I got which is something simple cs2 + metamode + css + admin, but when i get to admin addons I just can't figure how to implement it.

my logs are telling me that im missing admin.json.
if I create the admin.json, what is the format of the code there. Should I just use your last comment
