### ISSUE TITLE
crash server 

### ISSUE THREAD

**Issue by ezekutor** [roflmuffin/CounterStrikeSharp#326]
```
Unhandled exception. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Modules.Utils.CHandle`1.get_IsValid() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Utils/CHandle.cs:line 56
   at ServerInfo.ServerInfo.IsPlayerValid(CCSPlayerController player)
   at ServerInfo.ServerInfo.UpdatePlayerInfoAsync()
   at ServerInfo.ServerInfo.<OnRoundStart>b__59_1()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Using breakpad crash handler
```

**Comment by KillStr3aK** [comment]
seems to be related to `ServerInfo`

**Comment by ezekutor** [comment]
> кажется, связано с`ServerInfo`

Ok

**Comment by rogfish** [comment]
Updating seems to remove Game csgo/addons/metamod from gameinfo.gi and re-adding it breaks the server.

**Comment by ezekutor** [comment]
it happened a few hours after the update, when online on 22/32. I don't think that's the reason.

**Comment by ALegitCookie** [comment]
> ```
> Unhandled exception. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
>    at CounterStrikeSharp.API.Modules.Utils.CHandle`1.get_IsValid() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Utils/CHandle.cs:line 56
>    at ServerInfo.ServerInfo.IsPlayerValid(CCSPlayerController player)
>    at ServerInfo.ServerInfo.UpdatePlayerInfoAsync()
>    at ServerInfo.ServerInfo.<OnRoundStart>b__59_1()
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> Using breakpad crash handler
> ```

I was having this same problem and I think I either fixed it by doing a complete fresh install of cs2 server and cssharp, or I think I just updated cssharp and it started working. was rly random
