### ISSUE TITLE
NextFrame/NextWorldUpdate fails when nested

### ISSUE THREAD

**Issue by busheezy** [roflmuffin/CounterStrikeSharp#354]
It is not currently possible to nest NextFrame or NextWorldUpdate. 

```csharp
Server.NextFrame(() =>
{
  Server.NextFrame(() =>
  {
    Logger.LogInformation("Crash!");
  });
});
```

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at CounterStrikeSharp.API.Core.Helpers.InvokeNative(IntPtr ptr)
   at CounterStrikeSharp.API.Core.ScriptContext.InvokeNativeInternal() in C:\Users\Michael\source\repos\CounterStrikeSharp\managed\CounterStrikeSharp.API\Core\ScriptContext.cs:line 114
   at CounterStrikeSharp.API.Core.ScriptContext.Invoke() in C:\Users\Michael\source\repos\CounterStrikeSharp\managed\CounterStrikeSharp.API\Core\ScriptContext.cs:line 103
   at CounterStrikeSharp.API.Core.NativeAPI.QueueTaskForNextWorldUpdate(InputArgument callback) in C:\Users\Michael\source\repos\CounterStrikeSharp\managed\CounterStrikeSharp.API\Core\API.cs:line 520
   ```

**Comment by busheezy** [comment]
Additionally, a method RunOnTickCountN that allows you to schedule a task N ticks away would be great.

**Comment by KillStr3aK** [comment]
> Additionally, a method RunOnTickCountN that allows you to schedule a task N ticks away would be great.

I've posted a workaround that comes with much overhead in the discord server long time ago, we could benefit for sure from a built-in internal way to do this^
