### ISSUE TITLE
System.Exception: Unable to find plugin in assembly

### ISSUE THREAD

**Issue by barlap** [roflmuffin/CounterStrikeSharp#371]
Hello, 
I was using a plugin for name checker plugin but since I updated to the last cssharp version I get this error in the console:
From what I read I saw that is something related to null checks I tried to add multiple null checks but seems to be something related to cssharp itself.

System.Exception: Unable to find plugin in assembly
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 131
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
 
![error](https://github.com/roflmuffin/CounterStrikeSharp/assets/18375400/ec9166df-b756-4b5f-95ee-a26502048199)

**Comment by barlap** [comment]
Fixed, 
Looks like the original author didn't declared the class as public.
