### ISSUE TITLE
There is a bug in the hot overload of the overlay plugin

### ISSUE THREAD

**Issue by Nianmou** [roflmuffin/CounterStrikeSharp#420]
`08:47:53 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at McMaster.NETCore.Plugins.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path)
   at McMaster.NETCore.Plugins.PluginLoader.LoadDefaultAssembly()
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 126
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.<>c__DisplayClass29_0.<OnReloadedAsync>b__0() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 113
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
36.028558 UNEXPECTED LONG FRAME DETECTED: 28.44ms elapsed, 28.11ms sim time, 1 ticks, 2389..2389.
`

**Comment by roflmuffin** [comment]
Can you provide some more information, what is the Overlay Plugin?

**Comment by Nianmou** [comment]
It may be an issue with the translator, but I want to express that when I try to overwrite the plugin and reload it, it may report an error

> 您能否提供更多信息，什么是 Overlay 插件？

It may be an issue with the translator, but I want to express that when I try to overwrite the plugin and reload it, it may report an error

**Comment by roflmuffin** [comment]
Does this happen on every hot reload or only occasionally? I have seen this happen sometimes but not very often.

**Comment by KillStr3aK** [comment]
> Does this happen on every hot reload or only occasionally? I have seen this happen sometimes but not very often.

I've seen this issue when there were version changes between the dependencies for the plugin
