### ISSUE TITLE
GiveNamedItem(String item)

### ISSUE THREAD

**Issue by Mr-Robot-ops** [roflmuffin/CounterStrikeSharp#428]
I've been writing my first plugin over the last few weeks, working with CSharp. And yes, I'm aware that it's certainly not perfect. But after a lot of back and forth and testing, it finally did what I wanted it to do. 

And now, after yesterday's update of VALVE, my plugin no longer works, so I switched to version V215. Unfortunately without any change. I already tried to debug the whole thing and the weapon values are transferred correctly.

I know you guys are very busy at the moment and have more important things to do. Maybe someone can take a look at my makeshift code?

```
18:36:19 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1059
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternal[T](Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 72
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionWithReturn`7.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionWithReturn.cs:line 154
   at CounterStrikeSharp.API.Core.CCSPlayerController.GiveNamedItem(String item) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 26
   at DecoyPlugin.DecoyPlugin.GiveMissingWeapons(CCSPlayerController player, HashSet`1 expectedWeapons) in C:\Users\Censored\Documents\CSSHARP\test3\Decoy\Decoy.cs:line 93
   at DecoyPlugin.DecoyPlugin.<Load>b__6_2() in C:\Users\Censored\Documents\CSSHARP\test3\Decoy\Decoy.cs:line 53
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

[Gist-Decoy.cs GitHub](https://gist.github.com/Mr-Robot-ops/05571ea014abf33ea8e472a62b1a8173)

**Comment by roflmuffin** [comment]
I've just merged in a change to make givenameditem more resilient after updates, please try again with v216

**Comment by crashzk** [comment]
Linux subscription, does it need to be updated?

https://github.com/ianlucas/cs2-inventory-simulator-plugin/issues/7

**Comment by roflmuffin** [comment]
@crashzk Updated the linux sig in v218

**Comment by Mr-Robot-ops** [comment]
Thank you from the bottom of my heart for your quick response. Everything is working again
