### ISSUE TITLE
[ERROR] (cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by Kfalt** [roflmuffin/CounterStrikeSharp#429]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.UInt16.ToString()
   at Deathmatch.Deathmatch.OnWeaponCanAcquire(DynamicHook hook) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Events.cs:line 210
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  
===== End of inner exception stack trace =====
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100


2024-04-28 00:38:23.798 +02:00 [**ERROR**] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.UInt16.ToString()
   at Deathmatch.Deathmatch.OnWeaponCanAcquire(DynamicHook hook) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Events.cs:line 210
   at InvokeStub_Func`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   
===== End of inner exception stack trace =====
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionRefere
nce.cs:line 100 ```

**Comment by mrc4tt** [comment]
@Kfalt Update CS2-deathmatch. :-)
