### ISSUE TITLE
[EROR] (cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by mayersgamer** [roflmuffin/CounterStrikeSharp#438]
23:00:46 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Int32 ByRef CounterStrikeSharp.API.Core.CCSPlayerPawnBase.get_ArmorValue()'.
   at CS2_SimpleAdmin.CS2_SimpleAdmin.OnPlayerHurt(EventPlayerHurt event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by roflmuffin** [comment]
The plugin needs to be recompiled against cs# v215 (at least) as valve moved schema values around in last patch
