### ISSUE TITLE
Failed to load admin data

### ISSUE THREAD

**Issue by Geant200** [roflmuffin/CounterStrikeSharp#511]
Hello I have the latest version I encounter crashes and in my log file this is the result??.

Thanks in advance.

```
2024-06-23 17:28:29.925 +02:00 [EROR] (cssharp:AdminManager) Failed to load admin data
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at CounterStrikeSharp.API.Modules.Admin.AdminManager.LoadAdminData(String adminDataPath) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Admin/AdminPermissions.cs:line 129
```

```
2024-06-23 17:28:30.648 +02:00 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
2024-06-23 17:28:30.648 +02:00 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
2024-06-23 17:28:30.648 +02:00 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
2024-06-23 17:28:30.649 +02:00 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
2024-06-23 17:28:30.649 +02:00 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
2024-06-23 17:28:30.649 +02:00 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
```

**Comment by Geant200** [comment]
Thank you for your time for responding to my request.

The problem is that if I make several groups I would have to stop the server to change the map group or go through plugins and commands to change a group to play on the correct map cycle I wanted to use only one group so that the map cycle arrives all alone on maps of different game modes and with plugins to ensure that when the server arrives on a map of a particular game mode that the players have nothing to do.

I can ask you why a limit of 105 maps per group?

I remember when I was configuring servers in CSS with the Metamod SourceMode Eventscript ManiAdminPlugin plugin I could place more cards it would be possible for you to use the same principle sorry I am not developed to the point of being able to create a plugin ^^.

Thank you in advance ^^.

**Comment by roflmuffin** [comment]
Most likely cause is a permission issue on the admins json file in `/game/csgo/addons/counterstrikesharp/configs/admins.json` that prevents it from being read, or it is an empty file.
