### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by NikolaJyun** [roflmuffin/CounterStrikeSharp#536]
2024-08-04 14:17:31.533 +08:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Entity is not valid
   at CounterStrikeSharp.API.Guard.IsValidEntity(CEntityInstance ent) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Guard.cs:line 8
   at CounterStrikeSharp.API.Core.CCSPlayerController.PrintToChat(String message) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 51
   at RetakesAllocator.Helpers.WriteNewlineDelimited(String message, Action`1 writer) in C:\Users\NikolaJyun\Desktop\cs2-retakes-allocator-2.3.10\RetakesAllocator\Helpers.cs:line 23
   at RetakesAllocator.Menus.GunsMenu.Print(CCSPlayerController player, String message) in C:\Users\NikolaJyun\Desktop\cs2-retakes-allocator-2.3.10\RetakesAllocator\Menus\GunsMenu.cs:line 18
   at RetakesAllocator.Menus.GunsMenu.OnMenuTimeout(CCSPlayerController player) in C:\Users\NikolaJyun\Desktop\cs2-retakes-allocator-2.3.10\RetakesAllocator\Menus\GunsMenu.cs:line 41
   at RetakesAllocator.Menus.GunsMenu.<>c__DisplayClass5_0.<CreateMenuTimeoutTimer>b__0() in C:\Users\NikolaJyun\Desktop\cs2-retakes-allocator-2.3.10\RetakesAllocator\Menus\GunsMenu.cs:line 57
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by xLeviNx** [comment]
Not related to cs#. This is related to your cs retakes plugin.

**Comment by NikolaJyun** [comment]
Sure, thank you. I missed this when I checked.

**Comment by KillStr3aK** [comment]
> Sure, thank you. I missed this when I checked.

in that case you can close the issue
