### ISSUE TITLE
Unable to use Server.GetMapList()

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [roflmuffin/CounterStrikeSharp#551]
```
14:37:30 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Maplist.txt could not be found!
   at CounterStrikeSharp.API.Server.GetMapList() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Server.cs:line 147
   at KusunokiLib.KusunokiLib.ListMap(CCSPlayerController player) in D:\GitHub\KusunokiLib\KusunokiLib.cs:line 41
   at KusunokiLib.KusunokiLib.<Load>b__4_0(CCSPlayerController player, CommandInfo info)
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

![image](https://github.com/user-attachments/assets/7250b72d-badb-462b-9c48-a1f92c40dcdf)
Did I miss something like Maplist.txt and how can I get it?

**Comment by KillStr3aK** [comment]
You can create the file `maplist.txt` in the root of the game directory, however that method will probably return an empty array because it looks for `.bsp` files for some reason, this needs to be fixed but not sure if maps could even be downloaded without workshop
