### ISSUE TITLE
Failed to load ZombieSharp.dll due to invalid function pointer

### ISSUE THREAD

**Issue by Slush1998** [roflmuffin/CounterStrikeSharp#645]
Hello, i have spent hours trying to fix this problem, but now im about to give up, so this is my last attempt. Can someone pls help me understand why it dosent load. Thanks

09:12:20 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/ZombieSharp/ZombieSharp.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
at ZombieSharp.ZombieSharp.VirtualFunctionsInitialize() in E:\Github\ZombieSharp\ZombieSharp\VirtualFunctions.cs:line 38
at ZombieSharp.ZombieSharp.Load(Boolean HotReload) in E:\Github\ZombieSharp\ZombieSharp\ZombieSharp.cs:line 49
at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

**Comment by KillStr3aK** [comment]
Hey, one of the signatures might be wrong? maybe give us a hint about whats going on inside `ZombieSharp\VirtualFunctions.cs`

**Comment by Slush1998** [comment]
Hey thanks for replying, im not very good at this, but i cant find the ZombieSharp\VirtualFunctions.cs but should it be in this folder?
/game/csgo/addons/counterstrikesharp/plugins/ZombieSharp

![Udklip](https://github.com/user-attachments/assets/164b623b-ce9c-4325-b3ca-19b11c69604c)

**Comment by KillStr3aK** [comment]
That file is in the given plugin source code, seems like this issue is more related to the plugin itself rather than the CS# core
I believe one of the plugin dependencies has changed in the game and its not up to date with the latest one. maybe search for update or tell the developers that its outdated

**Comment by B3none** [comment]
https://github.com/oylsister/ZombieSharp/blob/main/ZombieSharp/VirtualFunctions.cs

**Comment by B3none** [comment]
As this is not an error with CounterStrikeSharp itself I'm going to close this issue. I'd recommend contacting the plugin's creator or posting an issue on their repo.
